# Generated by Django 3.2.8 on 2021-10-09 05:06

import dfuture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfuture', '0002_documentrequest_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=dfuture.models.upload_to, verbose_name='File')),
            ],
        ),
    ]
