# Generated by Django 3.2.8 on 2021-10-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfuture', '0003_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
