# Generated by Django 3.2.8 on 2021-10-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfuture', '0005_remove_document_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='uploaded',
        ),
    ]
